#!/usr/bin/env python3
"""Generate CSP distribution files: csp.h, csp.cpp, csp_globals.cpp, AGENTS-CSP.md"""

import re
import sys
from pathlib import Path

INCLUDE_RE = re.compile(r'^(\s*#\s*include\s+)([<"])([^>"]+)[>"](.*)$')
PRAGMA_ONCE_RE = re.compile(r'^\s*#\s*pragma\s+once\s*$')

# Preprocessor symbols treated as undefined when converting fcontext .S files.
FCONTEXT_UNDEF = {
    '__CET__', 'BOOST_USE_TSX', 'BOOST_CONTEXT_SHADOW_STACK',
    'BOOST_CONTEXT_TLS_STACK_PROTECTOR', '__i386__', '_ILP32',
    'SHSTK_ENABLED', 'SHADOW_STACK_SYSCALL',
}

PP_DIRECTIVES = {
    'if', 'ifdef', 'ifndef', 'elif', 'else', 'endif',
    'define', 'undef', 'include', 'pragma', 'error', 'warning', 'line',
}


def is_under(path, parent):
    try:
        path.relative_to(parent)
        return True
    except ValueError:
        return False


def amalgamate_headers(include_dir, seeds, output, banner, inline_pred, skip_pred):
    """
    Build a single header from seed files via DFS include resolution.

    inline_pred(resolved_path) → True: recursively inline this file
    skip_pred(resolved_path)   → True: silently drop the #include line
    Neither                    → keep the #include line verbatim
    """
    seen = set()
    lines = []

    def resolve(filepath):
        fp = filepath.resolve()
        if fp in seen:
            return
        seen.add(fp)

        try:
            rel = fp.relative_to(include_dir)
        except ValueError:
            rel = fp.name
        lines.append(f'\n/* {rel} */\n')

        with open(fp) as f:
            for line in f:
                if PRAGMA_ONCE_RE.match(line):
                    continue
                m = INCLUDE_RE.match(line)
                if m:
                    bracket, inc = m.group(2), m.group(3)
                    # Resolve the include path.
                    resolved = None
                    if bracket == '"':
                        p = fp.parent / inc
                        if p.exists():
                            resolved = p.resolve()
                    if resolved is None:
                        p = include_dir / inc
                        if p.exists():
                            resolved = p.resolve()

                    if resolved and inline_pred(resolved):
                        resolve(resolved)
                        continue
                    if resolved and skip_pred(resolved):
                        continue
                    # Unresolved csp/ includes that match skip_pred by name.
                    if resolved is None and skip_pred_name(inc):
                        continue

                lines.append(line)

    def skip_pred_name(inc):
        """Fallback: skip by include string when file can't be resolved."""
        return inc.startswith('csp/')

    for seed in seeds:
        resolve(seed)

    output.parent.mkdir(parents=True, exist_ok=True)
    with open(output, 'w') as f:
        f.write(f'/* {banner} */\n')
        f.write('/* Auto-generated by scripts/amalgamate.py — do not edit. */\n')
        f.write('#pragma once\n')
        for line in lines:
            f.write(line)

    print(f'  {output}  ({sum(1 for l in lines if l.strip())} non-blank lines)')


def amalgamate_sources(src_files, output, header, banner):
    """Build combined source from .cc/.cpp files."""
    lines = []

    for src in src_files:
        lines.append(f'\n/* {src.name} */\n')
        with open(src) as f:
            for line in f:
                if PRAGMA_ONCE_RE.match(line):
                    continue
                m = INCLUDE_RE.match(line)
                if m:
                    inc = m.group(3)
                    if inc.startswith('csp/'):
                        continue
                lines.append(line)

    output.parent.mkdir(parents=True, exist_ok=True)
    with open(output, 'w') as f:
        f.write(f'/* {banner} */\n')
        f.write('/* Auto-generated by scripts/amalgamate.py — do not edit. */\n')
        f.write(f'#include "{header}"\n')
        for line in lines:
            f.write(line)

    print(f'  {output}  ({sum(1 for l in lines if l.strip())} non-blank lines)')


# ---------------------------------------------------------------------------
# fcontext .S → inline asm() conversion
# ---------------------------------------------------------------------------

def _parse_pp(line):
    """Parse preprocessor directive. Returns (directive, rest) or None."""
    m = re.match(r'^#\s*(\w+)(.*)', line.strip())
    if m and m.group(1) in PP_DIRECTIVES:
        return m.group(1), m.group(2).strip()
    return None


def _eval_pp(directive, rest, undef):
    """Evaluate condition against undef set. Returns True/False/None."""
    rest = rest.strip()
    if directive == 'ifdef':
        return False if rest in undef else None
    if directive == 'ifndef':
        return True if rest in undef else None
    if directive == 'if':
        # !defined(X)
        m = re.match(r'^!\s*defined\s*\(?\s*(\w+)\s*\)?\s*$', rest)
        if m:
            return True if m.group(1) in undef else None
        # defined(X) ...
        m = re.match(r'^defined\s*\(?\s*(\w+)\s*\)?', rest)
        if m and m.group(1) in undef:
            return False
        # bare symbol
        m = re.match(r'^(\w+)\s*$', rest)
        if m and m.group(1) in undef:
            return False
        return None
    return None


def _preprocess(lines, undef):
    """Evaluate known #if conditions, stripping resolved blocks."""
    result = []
    stack = []  # entries: [active, determined, seen_true]

    def active():
        return all(e[0] for e in stack)

    for line in lines:
        pp = _parse_pp(line)
        if pp:
            d, rest = pp
            if d in ('if', 'ifdef', 'ifndef'):
                if not active():
                    stack.append([False, True, False])
                else:
                    val = _eval_pp(d, rest, undef)
                    if val is True:
                        stack.append([True, True, True])
                    elif val is False:
                        stack.append([False, True, False])
                    else:
                        result.append(line)
                        stack.append([True, False, True])
            elif d == 'else':
                if stack:
                    _, det, seen = stack[-1]
                    if det:
                        stack[-1] = [not seen, True, True]
                    elif active():
                        result.append(line)
            elif d == 'endif':
                if stack:
                    _, det, _ = stack.pop()
                    if not det and active():
                        result.append(line)
            # Strip #define, #include inside .S
            continue

        if active():
            result.append(line)

    return result


def _strip_leading_comments(lines):
    """Strip leading C-style comment blocks and blank lines."""
    i, in_comment = 0, False
    while i < len(lines):
        s = lines[i].strip()
        if not s:
            i += 1
            continue
        if in_comment:
            if '*/' in s:
                in_comment = False
            i += 1
            continue
        if s.startswith('/*'):
            in_comment = '*/' not in s[2:]
            i += 1
            continue
        break
    return lines[i:]


def _should_strip(line):
    """Lines to remove from assembly output."""
    s = line.strip()
    if s.startswith('.file ') or s.startswith('.file\t'):
        return True
    if '.note.GNU-stack' in s:
        return True
    if s == '_CET_ENDBR':
        return True
    return False


def _format_asm(buf):
    """Format assembly lines as a C++ asm() statement."""
    while buf and not buf[-1].strip():
        buf.pop()
    if not buf:
        return ''
    escaped = []
    for line in buf:
        raw = line.rstrip().replace('\\', '\\\\').replace('"', '\\"')
        escaped.append(f'"{raw}\\n"')
    return 'asm(\n' + '\n'.join(escaped) + '\n);'


_ADR_RE = re.compile(r'^(\s*)adr\s+(x\d+|lr|fp)\s*,\s*(\w+)\s*$')


def _fixup_adr(lines, is_macho):
    """Replace adr with adrp+add (adr relocations fail in inline asm)."""
    result = []
    for line in lines:
        m = _ADR_RE.match(line)
        if m:
            indent, reg, label = m.group(1), m.group(2), m.group(3)
            if is_macho:
                result.append(f'{indent}adrp {reg}, {label}@PAGE')
                result.append(f'{indent}add  {reg}, {reg}, {label}@PAGEOFF')
            else:
                result.append(f'{indent}adrp {reg}, {label}')
                result.append(f'{indent}add  {reg}, {reg}, :lo12:{label}')
        else:
            result.append(line)
    return result


def _convert_s(filepath, undef, is_macho=False):
    """Convert one .S file to C++ inline asm() blocks."""
    lines = filepath.read_text().splitlines()
    lines = _strip_leading_comments(lines)
    lines = _preprocess(lines, undef)
    lines = _fixup_adr(lines, is_macho)

    parts, buf = [], []
    for line in lines:
        if _should_strip(line):
            continue
        pp = _parse_pp(line)
        if pp:
            if buf:
                parts.append(_format_asm(buf))
                buf = []
            parts.append(line)
        else:
            buf.append(line)
    if buf:
        parts.append(_format_asm(buf))

    return '\n'.join(p for p in parts if p)


def amalgamate_fcontext(fcontext_dir, output):
    """Append fcontext inline assembly to csp.cpp."""
    variants = [
        ('__aarch64__', '_M_ARM64', '__APPLE__',
         'jump_arm64_aapcs_macho_gas.S', 'make_arm64_aapcs_macho_gas.S',
         'jump_arm64_aapcs_elf_gas.S',   'make_arm64_aapcs_elf_gas.S'),
        ('__x86_64__',  '_M_X64',  '__APPLE__',
         'jump_x86_64_sysv_macho_gas.S', 'make_x86_64_sysv_macho_gas.S',
         'jump_x86_64_sysv_elf_gas.S',   'make_x86_64_sysv_elf_gas.S'),
    ]

    sections = ['\n/* fcontext — context-switching primitives (from Boost.Context) */']

    for idx, (arch, arch_alt, plat, mj, mm, ej, em) in enumerate(variants):
        guard = f'#{"if" if idx == 0 else "elif"} defined({arch}) || defined({arch_alt})'
        sections.append(guard)

        sections.append(f'#if defined({plat})')
        sections.append(f'/* {mj} */')
        sections.append(_convert_s(fcontext_dir / mj, FCONTEXT_UNDEF, is_macho=True))
        sections.append(f'/* {mm} */')
        sections.append(_convert_s(fcontext_dir / mm, FCONTEXT_UNDEF, is_macho=True))

        sections.append('#else /* ELF */')
        sections.append(f'/* {ej} */')
        sections.append(_convert_s(fcontext_dir / ej, FCONTEXT_UNDEF, is_macho=False))
        sections.append(f'/* {em} */')
        sections.append(_convert_s(fcontext_dir / em, FCONTEXT_UNDEF, is_macho=False))
        sections.append(f'#endif /* {plat} */')

    sections.append('#else')
    sections.append('#error "Unsupported architecture for CSP fcontext"')
    sections.append('#endif')

    text = '\n'.join(sections) + '\n'
    with open(output, 'a') as f:
        f.write(text)

    count = sum(1 for line in text.splitlines() if line.strip())
    print(f'  (appended fcontext assembly: {count} non-blank lines)')


def dedup_includes(filepath):
    """Remove duplicate #include lines from a generated file."""
    with open(filepath) as f:
        lines = f.readlines()

    seen = set()
    out = []
    removed = 0
    for line in lines:
        m = INCLUDE_RE.match(line)
        if m:
            key = m.group(2) + m.group(3)
            if key in seen:
                removed += 1
                continue
            seen.add(key)
        out.append(line)

    if removed:
        with open(filepath, 'w') as f:
            f.writelines(out)
        print(f'  {filepath}: removed {removed} duplicate include(s)')


def generate_gateway(include_dir, csp_dir):
    """Generate include/csp.h — gateway header that includes all public headers."""
    headers = sorted(csp_dir.rglob('*.h'))
    gateway = include_dir / 'csp.h'

    with open(gateway, 'w') as f:
        f.write('/* CSP — gateway header (includes all public headers) */\n')
        f.write('/* Auto-generated by scripts/amalgamate.py — do not edit. */\n')
        f.write('#pragma once\n')
        for h in headers:
            rel = h.relative_to(include_dir)
            f.write(f'#include "{rel}"\n')

    print(f'  {gateway}  ({len(headers)} headers)')


AGENTS_INTEGRATION = """\
## Integration

Copy these files into your project:

| File | Purpose |
|---|---|
| `csp.h` | Single header (all public API) |
| `csp.cpp` | Implementation + context-switching assembly |
| `csp_globals.cpp` | Thread-local state (**must** be a separate translation unit — see [docs/tls-caching-bug.md](https://github.com/marcelocantos/csp/blob/master/docs/tls-caching-bug.md)) |
| `AGENTS-CSP.md` | This file — agent reference for CSP |

Compile with C++20 and libc++:

```bash
c++ -std=c++20 -O2 -c csp.cpp -o csp.o
c++ -std=c++20 -O2 -c csp_globals.cpp -o csp_globals.o
```

Reference this file from your project's `CLAUDE.md` or `AGENTS.md` to
give coding agents CSP expertise.
"""


def generate_agents_guide(docs_dir, out_dir):
    """Generate AGENTS-CSP.md from docs/agent-guide.md with Build section replaced."""
    source = docs_dir / 'agent-guide.md'
    output = out_dir / 'AGENTS-CSP.md'

    with open(source) as f:
        content = f.read()

    # Replace the Build section (## Build ... to end of file or next ## heading)
    # The Build section is at the end of agent-guide.md.
    build_re = re.compile(r'\n## Build\n.*', re.DOTALL)
    content = build_re.sub('\n' + AGENTS_INTEGRATION, content)

    with open(output, 'w') as f:
        f.write(content)

    lines = sum(1 for line in content.splitlines() if line.strip())
    print(f'  {output}  ({lines} non-blank lines)')


def main():
    root = Path(__file__).resolve().parent.parent
    include_dir = root / 'include'
    src_dir = root / 'src'
    docs_dir = root / 'docs'
    out_dir = root / 'dist'

    csp_dir = include_dir / 'csp'
    part_dir = csp_dir / 'part'

    # --- include/csp.h: gateway that includes all public headers ---
    print('include/csp.h:')
    generate_gateway(include_dir, csp_dir)

    # --- csp.h: all headers under include/csp/ (core + part/) ---
    all_seeds = sorted(csp_dir.rglob('*.h'))
    print('csp.h:')
    amalgamate_headers(
        include_dir, all_seeds,
        out_dir / 'csp.h', 'CSP — single header',
        inline_pred=lambda p: is_under(p, csp_dir),
        skip_pred=lambda p: False,
    )

    # --- csp.cpp: all source files except csp_globals.cpp ---
    # csp_globals.cpp MUST be a separate TU.  It defines the
    # thread_local variable g_imp.  When the definition and the
    # extern declaration (from csp_internal.h) are in the same TU,
    # Clang generates direct TLV-descriptor access and may cache the
    # resolved TLS address across jump_fcontext calls.  Because
    # jump_fcontext can resume an imp on a different OS thread,
    # the cached address becomes stale and writes to the wrong TLS
    # slot — corrupting g_imp and crashing the M:N scheduler.
    # Keeping csp_globals.cpp separate forces the wrapper-call
    # pattern, which re-resolves the TLS address on every access.
    globals_file = src_dir / 'csp_globals.cpp'
    src_files = sorted(
        p for p in (list(src_dir.glob('*.cc')) + list(src_dir.glob('*.cpp')))
        if p.resolve() != globals_file.resolve()
    )
    print('csp.cpp:')
    amalgamate_sources(
        src_files, out_dir / 'csp.cpp', 'csp.h',
        'CSP — implementation source',
    )

    # --- csp_globals.cpp: thread-local state (separate TU) ---
    print('csp_globals.cpp:')
    amalgamate_sources(
        [globals_file], out_dir / 'csp_globals.cpp', 'csp.h',
        'CSP — globals (separate TU for TLS correctness)',
    )

    # --- Append fcontext inline assembly to csp.cpp ---
    fcontext_dir = root / 'vendor' / 'github.com' / 'boostorg' / 'context' / 'src' / 'asm'
    if fcontext_dir.exists():
        amalgamate_fcontext(fcontext_dir, out_dir / 'csp.cpp')

    # --- Remove duplicate #include lines ---
    for f in sorted(out_dir.glob('*.cpp')) + sorted(out_dir.glob('*.h')):
        dedup_includes(f)

    # --- AGENTS-CSP.md: agent reference guide ---
    print('AGENTS-CSP.md:')
    generate_agents_guide(docs_dir, out_dir)


if __name__ == '__main__':
    main()
