#!/usr/bin/env python3
"""Generate CSP amalgamation files: csp.h, csp.cpp, csp_parts.h"""

import re
import sys
from pathlib import Path

INCLUDE_RE = re.compile(r'^(\s*#\s*include\s+)([<"])([^>"]+)[>"](.*)$')
PRAGMA_ONCE_RE = re.compile(r'^\s*#\s*pragma\s+once\s*$')


def is_under(path, parent):
    try:
        path.relative_to(parent)
        return True
    except ValueError:
        return False


def amalgamate_headers(include_dir, seeds, output, banner, inline_pred, skip_pred):
    """
    Build an amalgamated header from seed files via DFS include resolution.

    inline_pred(resolved_path) → True: recursively inline this file
    skip_pred(resolved_path)   → True: silently drop the #include line
    Neither                    → keep the #include line verbatim
    """
    seen = set()
    lines = []

    def resolve(filepath):
        fp = filepath.resolve()
        if fp in seen:
            return
        seen.add(fp)

        try:
            rel = fp.relative_to(include_dir)
        except ValueError:
            rel = fp.name
        lines.append(f'\n/* {rel} */\n')

        with open(fp) as f:
            for line in f:
                if PRAGMA_ONCE_RE.match(line):
                    continue
                m = INCLUDE_RE.match(line)
                if m:
                    bracket, inc = m.group(2), m.group(3)
                    # Resolve the include path.
                    resolved = None
                    if bracket == '"':
                        p = fp.parent / inc
                        if p.exists():
                            resolved = p.resolve()
                    if resolved is None:
                        p = include_dir / inc
                        if p.exists():
                            resolved = p.resolve()

                    if resolved and inline_pred(resolved):
                        resolve(resolved)
                        continue
                    if resolved and skip_pred(resolved):
                        continue
                    # Unresolved csp/ includes that match skip_pred by name.
                    if resolved is None and skip_pred_name(inc):
                        continue

                lines.append(line)

    def skip_pred_name(inc):
        """Fallback: skip by include string when file can't be resolved."""
        return inc.startswith('csp/')

    for seed in seeds:
        resolve(seed)

    output.parent.mkdir(parents=True, exist_ok=True)
    with open(output, 'w') as f:
        f.write(f'/* {banner} */\n')
        f.write('/* Auto-generated by scripts/amalgamate.py — do not edit. */\n')
        f.write('#pragma once\n')
        for line in lines:
            f.write(line)

    print(f'  {output}  ({sum(1 for l in lines if l.strip())} non-blank lines)')


def amalgamate_sources(src_files, output, header, banner):
    """Build source amalgamation from .cc/.cpp files."""
    lines = []

    for src in src_files:
        lines.append(f'\n/* {src.name} */\n')
        with open(src) as f:
            for line in f:
                if PRAGMA_ONCE_RE.match(line):
                    continue
                m = INCLUDE_RE.match(line)
                if m:
                    inc = m.group(3)
                    if inc.startswith('csp/'):
                        continue
                lines.append(line)

    output.parent.mkdir(parents=True, exist_ok=True)
    with open(output, 'w') as f:
        f.write(f'/* {banner} */\n')
        f.write('/* Auto-generated by scripts/amalgamate.py — do not edit. */\n')
        f.write(f'#include "{header}"\n')
        for line in lines:
            f.write(line)

    print(f'  {output}  ({sum(1 for l in lines if l.strip())} non-blank lines)')


def main():
    root = Path(__file__).resolve().parent.parent
    include_dir = root / 'include'
    src_dir = root / 'src'
    out_dir = root / 'amalg'

    csp_dir = include_dir / 'csp'
    part_dir = csp_dir / 'part'

    # --- csp.h: all headers under include/csp/ except part/ ---
    core_seeds = sorted(
        p for p in csp_dir.rglob('*.h')
        if not is_under(p, part_dir)
    )
    print('csp.h:')
    amalgamate_headers(
        include_dir, core_seeds,
        out_dir / 'csp.h', 'CSP — amalgamated header',
        inline_pred=lambda p: is_under(p, csp_dir) and not is_under(p, part_dir),
        skip_pred=lambda p: False,
    )

    # --- csp_parts.h: all part/ headers ---
    part_seeds = sorted(part_dir.glob('*.h'))
    print('csp_parts.h:')
    amalgamate_headers(
        include_dir, part_seeds,
        out_dir / 'csp_parts.h', 'CSP parts — amalgamated header',
        inline_pred=lambda p: is_under(p, part_dir),
        skip_pred=lambda p: is_under(p, csp_dir),
    )

    # --- csp.cpp: all source files ---
    src_files = sorted(
        list(src_dir.glob('*.cc')) + list(src_dir.glob('*.cpp'))
    )
    print('csp.cpp:')
    amalgamate_sources(
        src_files, out_dir / 'csp.cpp', 'csp.h',
        'CSP — amalgamated source',
    )


if __name__ == '__main__':
    main()
